apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-survey-form
  labels: 
    app: cs-survey-form
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app: cs-survey-form
  template:
    metadata:
      labels: 
        app: cs-survey-form
    spec:
      containers:
      - name: cs-survey-form
        image: pavankoppula/studentsurvey645:tagversion
        ports:
        - {name: tomcat, containerPort: 8080}
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: swe645-cs-survey-service-name
spec:
  selector: 
    app: cs-survey-form
  ports:
  - {name: tomcat, protocol: TCP, port: 8300, targetPort: 8080}
  type: LoadBalancer